-- Create testimonials table (idempotent)
CREATE TABLE IF NOT EXISTS public.testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guest_name TEXT NOT NULL,
  guest_country TEXT,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  content TEXT NOT NULL,
  approved BOOLEAN NOT NULL DEFAULT FALSE,
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS testimonials_approved_idx ON public.testimonials (approved);
CREATE INDEX IF NOT EXISTS testimonials_featured_idx ON public.testimonials (featured);
CREATE INDEX IF NOT EXISTS testimonials_created_at_idx ON public.testimonials (created_at DESC);
